name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: docker run -v "${{ github.workspace }}:C:\Source" ghcr.io/enlyze/windows-build-environment powershell \Source\build.ps1

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Wizard-2020 Executable and PDB
        path: build/Release/Wizard-2020/bin/Wizard-2020.*
